# Site settings
title:          ppalmer.io
description:    "A blog about software development"
url:            "https://ppalmer.io"

# Author
author:
  name:         Patrick Palmer
  url:          https://ppalmer.io
  email:        ppalmer@pm.me

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
